name: Go test

on: push

jobs: 
  
  build:
    
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.3'

      - name: Build
        run: go build -o main -v ./...
      
      - name: Test with the Go CLI
        run: go test

      - name: UUID
        run: go install github.com/timwmillard/uuid@latest

      - name: Image name
        run: |
          echo "IMAGE_NAME=ttl.sh/$(uuid):1m" >> $GITHUB_ENV

      - name: Docker
        run: docker buildx build -f Containerfile -t ${{ env.IMAGE_NAME }} .

      - name: Push
        run: docker push ${{ env.IMAGE_NAME }}

      - name: Persist image name
        run: echo ${{ env.IMAGE_NAME }} > imgname.tmp

      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          source: "imgname.tmp,compose.yml"
          target: ~/goilerplate_deploy

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd goilerplate_deploy
            echo "IMAGE_NAME="$(cat imgname.tmp) > .env
            docker compose up
